#server:
#  port: 8761
#  
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://9.203.106.22:8761/eureka
#  instance:
#    hostname: 9.203.106.22
#    prefer-ip-address: true

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false